### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by FdezRomero** [keymetrics/pmx#11]
Our production app is being restarted frequently because of the following exception from `pmx` (v0.3.5), so we were forced to disable this module. If you need more information or logs just let me know.

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target.send (child_process.js:461:23)
    at ipcSend (/home/sl-node/extractor/node_modules/pmx/lib/utils/transport.js:21:13)
    at Object.Transport.send (/home/sl-node/extractor/node_modules/pmx/lib/utils/transport.js:32:3)
    at errorHandler (/home/sl-node/extractor/node_modules/pmx/lib/notify.js:109:15)
    at Layer.handle_error (/home/sl-node/extractor/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/home/sl-node/extractor/node_modules/express/lib/router/index.js:300:13)
    at /home/sl-node/extractor/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/sl-node/extractor/node_modules/express/lib/router/index.js:321:12)
    at next (/home/sl-node/extractor/node_modules/express/lib/router/index.js:261:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1693:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1588:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

**Comment by jorge-d** [comment]
Hi @FdezRomero,

Hum... this looks to be coming from the [express error handler](https://github.com/keymetrics/pmx/blob/master/lib/notify.js#L98-L114),
Do you have any issue with **pmx** if you don't call `pmx.expressErrorHandler()` in your code ? Do you have any hint on which express error could have triggered that circular structure ?

**Comment by FdezRomero** [comment]
Hi @jorge-d,

I tried requiring **pmx** without calling `app.use(pmx.expressErrorHandler())` and it works just fine. I don't know which error caused this as we have stdout errors disabled in production for performance reasons, which is one of the reasons we were using Keymetrics.

**Comment by jorge-d** [comment]
Great, however I wonder which express error was causing this... which version of express are you using and do you have any code sample / example of the piece of your code that was causing this?

**Comment by FdezRomero** [comment]
We developed the app in several small middleware modules but as the stack trace doesn't provide any indication that it occurred in any of our middleware, we think is coming from the Express router directly. We are using Express v4.12.3 on Node v0.10.35

**Comment by stringbeans** [comment]
We are experiencing this issue as well.

Using Express v4.12.4 on Node 0.12.3

**Comment by Unitech** [comment]
I think it's because of one of these [assignments](https://github.com/keymetrics/pmx/blob/master/lib/notify.js#L103), sometime [session](https://github.com/keymetrics/pmx/blob/master/lib/notify.js#L107) can have references to other objects. One of the solution would be to use https://www.npmjs.com/package/json-stringify-safe

**Comment by Unitech** [comment]
Or we can directly use json-stringify-safe [here](https://github.com/keymetrics/pmx/blob/master/lib/utils/transport.js#L21) (dup #16 )

**Comment by stringbeans** [comment]
thanks for the fix @Unitech ! 

ive done an npm update but have not received the changes. do you know when i will be able to pull in the changes?
