### ISSUE TITLE
cannot find module semver

### ISSUE THREAD

**Issue by dreaganluna** [keymetrics/pmx#117]
please fix, this is breaking a lot of our automated builds.
since about an hout ago:

`Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\inetpub\wwwroot\pricecalc\node_modules\pmx\lib\probes\deep_metrics.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)`

**Comment by vmarchaud** [comment]
We are re-publishing with the patch in the next minutes

**Comment by wallet77** [comment]
Done.

**Comment by dreaganluna** [comment]
you're the bomb! 👍
