### ISSUE TITLE
Node 0.12 pmx did not self register Errors?

### ISSUE THREAD

**Issue by ninjada** [keymetrics/pmx#45]
hi all, recently updated from 0.10.39 to 0.12.7 and my apps are constantly restarting or failing. only thing showing in error logs is the following:

```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ec2-user/node/qa-app/versions/20150819-101531/app/node_modules/cld/index.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

any ideas? 

ive tried many uninstall / reinstalls and npm rebuilds etc. no luck.

downgrading to 0.10 has no problems, but issue is i am moving to 0.12

**Comment by otobrglez** [comment]
I have the same issue. Anything now about this? Thanks!

**Comment by alavit-d** [comment]
Hi, this could be an issue coming from npm where the npm rebuild id not done correctly. Have you tried removing the node_modules folder and installing them again? Run the following commands: 
```shell
npm rebuild
rm -rf node_modules
npm install
```

**Comment by Unitech** [comment]
fixed
