### ISSUE TITLE
 Error: Cannot find module 'connect-flash'

### ISSUE THREAD

**Issue by lklepner** [keymetrics/pmx#57]
Trying to add PMX to an Express 4.9.8 app running under pm2 15.10 I get an error that connect-flash cannot be found. 

The full error reads - 
Error: Cannot find module 'connect-flash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.<anonymous> (/myapp/node_modules/pmx/lib/transaction.js:47:40)
   at Module.require (module.js:365:17)
  at require (module.js:384:17)
    at /myapp/app.js:99:17
    at /myapp/node_modules/mongodb/lib/mongo_client.js:455:11
   at process._tickDomainCallback (node.js:381:11)

"connect-flash": "^0.1.1" is present in the present in the package.json and node_modules folder. 

Any ideas what might be wrong?

Thanks,
Lou

**Comment by lklepner** [comment]
duplicate of #34
