### ISSUE TITLE
Cannot find module 'pm2'

### ISSUE THREAD

**Issue by milosjovac** [keymetrics/pmx#69]
Tis is my log:  

    Error: Cannot find module 'pm2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

OS: OS X 10.11.5
npm -v  : 2.15.1
node -v : 4.4.4
pm2 -v  : 1.1.3

`pm2` is installed globally with `npm install pm2 -g`. Instance is up and running with `pm2 start script.js`, so `pm2` is globally visible 100%. Further more I can reach the instance over the localhost, but on this part of the code: 

    var pm2 = require('pm2');

instance is crashed and log from the above is shown in console. I tried to install `pmx` as a global module `version 0.6.2` and to delete it locally from `node_modules` in `pm2`, but error remains.

Any idea what could be wrong?

**Comment by milosjovac** [comment]
This happens with all global packages, it was not a `pmx` issue. Key in solving this was linking global packages with the `npm`:

    $ npm link pm2

Many StackOverflow answers suggest setting the `$NODE_PATH`, but that was not enough in my case.
