### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mihailstefanov** [keymetrics/pmx#70]
When I using it with pm2 I get such error
pm2 1.1.3
node v5.11.1
Is it possible to disable this module?
TypeError: Cannot convert undefined or null to object
    at getOwnPropertyNames (native)
    at Function.assign (/home/mihail/blue-vending/node_modules/traceur/bin/traceur-runtime.js:163:19)
    at process.target.send (internal/child_process.js:518:22)
    at ipcSend (/usr/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:22:13)
    at Object.Transport.send (/usr/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:33:3)
    at Timeout._repeat (/usr/lib/node_modules/pm2/node_modules/pmx/lib/Probe.js:120:17)
    at Timeout.wrapper [as _onTimeout](timers.js:408:11)
    at Timer.unrefdHandle (timers.js:445:14)
Process disconnected from parent !

**Comment by vmarchaud** [comment]
Problem come from this module : `home/mihail/blue-vending/node_modules/traceur/bin/traceur-runtime.js:163:19` not from pmx.
