### ISSUE TITLE
pmx causing PM2 services to restart

### ISSUE THREAD

**Issue by jerrymannel** [keymetrics/pmx#71]
The following commit (https://github.com/keymetrics/pmx/commit/94caac9969fbc787bd6d4ab4c961cc43137ec5fa) is causing my PM2 service to restart with the following error.

> TypeError: Cannot read property 'length' of null
    at process.uncaughtListener (/usr/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:39:14)
    at process.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at emitPendingUnhandledRejections (node.js:501:24)
    at process._tickDomainCallback (node.js:413:9)

If i replace the pmx folder with an older version under pm2/node_modules it works fine.

These restarts are only happening on apps from which i'm serving static html pages. All other API based express apps are working fine.

> OS - Ubuntu 14.04 x86_64
> node - v4.5.0
> npm - 2.15.9
> pm2 - 1.1.3

**Comment by Unitech** [comment]
Fixed on 0.6.8, you just need to update your PM2 to get the latest PMX version

**Comment by jerrymannel** [comment]
Thanks, the issue has been fixed!
