### ISSUE TITLE
Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by finom** [keymetrics/pmx#82]
Thrown by `pmx.notify({ message: 'Failed to export DB', error });`

```
TypeError: Cannot read property 'filename' of undefined
    at findPackageJson (/home/webdev/apps/shopmonkey/staging/source/node_modules/pmx/lib/configuration.js:24:56)
    at Object.Options.init (/home/webdev/apps/shopmonkey/staging/source/node_modules/pmx/lib/configuration.js:43:26)
    at Object.<anonymous> (/home/webdev/apps/shopmonkey/staging/source/node_modules/pmx/lib/pmx.js:31:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

Any ideas how to fix?

**Comment by vmarchaud** [comment]
Which version of pm2/nodejs do you use ?

**Comment by finom** [comment]
@vmarchaud it fixed in new version. Sorry for long response.

**Comment by johnwebbcole** [comment]
I'm getting a similar issue
node 8.4.0 npm 5.3.0, pm2 2.6.1 and pmx 1.4.0

This is starting with `jest` to run unit tests.

```
var pkg_path = path.resolve(path.dirname(require.main.filename), 'packa
ge.json');
                                                       ^

TypeError: Cannot read property 'filename' of undefined
    at findPackageJson (D:\src\gateway-service\node_modules\pmx\lib\Confi
guration.js:23:56)
    at Object.<anonymous>.Configuration.initConf (D:\src\gateway-service\
node_modules\pmx\lib\Configuration.js:42:26)
    at Object.<anonymous> (D:\src\gateway-service\node_modules\pmx\lib\in
dex.js:49:31)
    at Runtime._execModule (D:\src\gateway-service\node_modules\jest-runt
ime\build\index.js:513:13)
    at Runtime.requireModule (D:\src\gateway-service\node_modules\jest-ru
ntime\build\index.js:329:14)
    at Runtime.requireModuleOrMock (D:\src\gateway-service\node_modules\j
est-runtime\build\index.js:405:19)
    at Object.<anonymous> (D:\src\gateway-service\node_modules\pmx\index.
js:2:28)
    at Runtime._execModule (D:\src\gateway-service\node_modules\jest-runt
ime\build\index.js:513:13)
    at Runtime.requireModule (D:\src\gateway-service\node_modules\jest-ru
ntime\build\index.js:329:14)
    at Runtime.requireModuleOrMock (D:\src\gateway-service\node_modules\j
est-runtime\build\index.js:405:19)
    at Object.<anonymous> (D:\src\gateway-service\app.js:12:11)
    at Runtime._execModule (D:\src\gateway-service\node_modules\jest-runt
ime\build\index.js:513:13)
    at Runtime.requireModule (D:\src\gateway-service\node_modules\jest-ru
ntime\build\index.js:329:14)
    at Runtime.requireModuleOrMock (D:\src\gateway-service\node_modules\j
est-runtime\build\index.js:405:19)
    at Server.<anonymous> (D:\src\gateway-service\test\index.test.js:104:
15)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1349:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by glortho** [comment]
The Jest issue may be related to this https://github.com/facebook/jest/issues/2150

**Comment by sauliusgrigaitis** [comment]
Getting error with node 8.8.1, pm2 2.7.2
```
(node:24275) ExperimentalWarning: The ESM module loader is experimental.
TypeError: Cannot read property 'filename' of undefined
    at findPackageJson (/usr/lib/node_modules/pm2/node_modules/pmx/lib/configuration.js:24:57)
    at Object.Options.init (/usr/lib/node_modules/pm2/node_modules/pmx/lib/configuration.js:43:26)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/pmx.js:31:31)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
```

**Comment by vmarchaud** [comment]
@sauliusgrigaitis checkout https://github.com/keymetrics/pmx/pull/101

**Comment by sauliusgrigaitis** [comment]
Thanks @vmarchaud
