### ISSUE TITLE
Cannot find module 'chalk' ?

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pmx#90]
I do not use chalk at all and since I've linked pm2 to keymetrics I get this weird error:

```
0|plant    | Error: Cannot find module 'chalk'
0|plant    |     at Function.Module._resolveFilename (module.js:485:15)
0|plant    |     at Function.Module._load (module.js:437:25)
0|plant    |     at Function._load (/home/pi/.nvm/versions/node/v8.1.0/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
0|plant    |     at Module.require (module.js:513:17)
0|plant    |     at require (internal/module.js:11:18)
0|plant    |     at Object.<anonymous> (/home/pi/autoplant/node_modules/johnny-five/lib/board.js:16:13)
0|plant    |     at Module._compile (module.js:569:30)
0|plant    |     at Object.Module._extensions..js (module.js:580:10)
0|plant    |     at Module.load (module.js:503:32)
0|plant    |     at tryModuleLoad (module.js:466:12)
```

**Comment by Unitech** [comment]
looks like internal bug
