### ISSUE TITLE
Transaction Tracing fail

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pmx#98]
```
TypeError: Cannot redefine property: stream -
at Function.defineProperty ()
at RedisClient.create_stream_trace (/home/ubuntu/node_modules/vxx/src/plugins/plugin-redis.js:36:16)
at RedisClient.create_stream_trace [as create_stream] (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/plugins/plugin-redis.js:44:28)
at new RedisClient (/home/ubuntu/node_modules/redis/index.js:161:10)
at exports.createClient (/home/ubuntu//node_modules/redis/index.js:1081:12)
at createClientTrace (/home/ubuntu/node_modules/vxx/src/plugins/plugin-redis.js:24:33)
at createClientTrace (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/plugins/plugin-redis.js:24:33)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Function.Module_load (/usr/local/lib/node_modules/pm2/node_modules/vxx/src/trace-plugin-loader.js:168:33)
at Function. (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
at Function.Module_load (/home/ubuntu/node_modules/vxx/src/trace-plugin-loader.js:168:33)
```

@vmarchaud does a potential upgrade of vxx could fix this issue?

**Comment by arpithparikh** [comment]
Please give me update if you guys could fix the bug! Generally, I'm getting this type-error while tracing the APIs using pm2.

**Comment by arpithparikh** [comment]
@vmarchaud any update about this issue?

**Comment by Unitech** [comment]
moving to https://github.com/keymetrics/keymetrics-support/issues/122
