### ISSUE TITLE
pmx@1.5.3 release issue

### ISSUE THREAD

**Issue by robiXxu** [keymetrics/pmx#99]
```
TypeError: Cannot read property 'R_OK' of undefined
   at look_for_profiler (/usr/lib/node_modules/pm2/node_modules/pmx/lib/probes/profiling.js:108:53)
   at Object.Profiling.detectV8Profiler (/usr/lib/node_modules/pm2/node_modules/pmx/lib/probes/profiling.js:119:5)
   at Object.Profiling.v8Profiling (/usr/lib/node_modules/pm2/node_modules/pmx/lib/probes/profiling.js:123:13)
   at Object.PMX.init (/usr/lib/node_modules/pm2/node_modules/pmx/lib/pmx.js:78:15)
   at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:8:18)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Function.Module.runMain (module.js:497:10)
```

**Comment by Unitech** [comment]
Which Node.js version?

**Comment by Unitech** [comment]
That's weird we do a check there: https://github.com/keymetrics/pmx/blob/master/lib/probes/profiling.js#L108

```
 fs.access(profiler_path, fs.R_OK || fs.constants.R_OK, function(err) {
```

**Comment by robiXxu** [comment]
node version : 0.10.48
(not my decision)

**Comment by alincalinciuc** [comment]
```
rm -rf /usr/lib/node_modules/pm2/node_modules/pmx
cd /usr/lib/node_modules/pm2 && npm install pmx@1.5.2
```

**Comment by robiXxu** [comment]
fs.access doesn't exist in that version
https://nodejs.org/dist/latest-v0.10.x/docs/api/fs.html

**Comment by Unitech** [comment]
Could one of you make a quick PR to fix this?

**Comment by robiXxu** [comment]
Made one. 
Let me know if that's ok with you.

**Comment by jacopolanzoni** [comment]
Same for Node v0.10.46

**Comment by Unitech** [comment]
pmx@1.5.4 has been published

Thanks to @robiXxu !
